language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email:
    - keith.andrew.j@gmail.com
branches:
  except:
  - robust
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("IncrementalPruning"); Pkg.test("IncrementalPruning"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("IncrementalPruning")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
