language: julia
os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.2

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("IncrementalPruning")); import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
